# Generated by Django 4.1.3 on 2023-01-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_course_techs'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='skills',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
