# Generated by Django 4.1.3 on 2023-01-25 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_teacher_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='address',
        ),
    ]
