# Generated by Django 4.1.3 on 2023-04-17 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_teacher_detail_alter_course_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='mobile_no',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='qualification',
        ),
    ]
