# Generated by Django 4.1.3 on 2023-04-20 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_teacher_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='profile_img',
        ),
    ]
