# Generated by Django 4.2 on 2023-04-20 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    	('main', '0022_teacher_profile_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentfavoritecourse',
            options={'verbose_name_plural': '11. Student Favorite Courses'},
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='profile_img',
        ),
    ]
