# Generated by Django 4.1.3 on 2023-04-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_studentassignment_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notifiread_status',
            field=models.BooleanField(default=False, verbose_name='Notification status'),
        ),
    ]
