# Generated by Django 4.1.3 on 2023-04-23 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_quiz_quizquestions_coursequiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.teacher'),
        ),
    ]
