# Generated by Django 4.1.3 on 2023-04-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_quiz_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='detail',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
