# Generated by Django 4.1.3 on 2023-04-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_quiz_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='detail',
            field=models.TextField(null=True),
        ),
    ]
