# Generated by Django 4.1.3 on 2023-05-02 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_quiz_detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name_plural': '08. Chapters'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': '06. Contact Queries'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': '03. Courses'},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name_plural': '02. Course Categories'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name_plural': '07. Faq'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name_plural': '05. Notifications'},
        ),
        migrations.AlterModelOptions(
            name='quizquestions',
            options={'verbose_name_plural': '15. Quiz Questions'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '04. Students'},
        ),
        migrations.AlterModelOptions(
            name='studentcourseenrollment',
            options={'verbose_name_plural': '09. Enrolled Courses'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': '01. Teachers'},
        ),
        migrations.RemoveField(
            model_name='coursequiz',
            name='Course',
        ),
        migrations.AddField(
            model_name='coursequiz',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.teacher'),
        ),
        migrations.AddField(
            model_name='coursequiz',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
    ]
