# Generated by Django 4.1.3 on 2023-05-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_attempquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempquiz',
            name='right_ans',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
